### ISSUE TITLE
大老 可否提供最新固件?

### ISSUE THREAD

**Issue by 0x55xx5** [fxsheep/jm20339_rom_dumper#1]
我有一個十年前的usbadapter chip

![jm2033firmver](https://github.com/user-attachments/assets/f0167af0-1df6-4337-a0ae-7041a6821f2a)
![image](https://github.com/user-attachments/assets/2f18ea22-c9c4-46b0-b874-73a1015aebbe)

![thumbnail_IMG_4937](https://github.com/user-attachments/assets/779ed7d1-75b5-4a7a-abea-dd4b4f168842)

目前在win10 上面無法辨識
![image](https://github.com/user-attachments/assets/88ea2dec-21e2-4368-a009-f284b0d8c4fb)
![image](https://github.com/user-attachments/assets/469ddc53-3830-4542-9255-49cf000b0ee5)

![IMG_4941](https://github.com/user-attachments/assets/c01f7ca9-1a97-4e56-9607-fef10ac86b11)

我猜可能是固件太老問題  

但我找不到相關的升級固件 可以提供我 dumper出來的固件嗎?

**Comment by 0x55xx5** [comment]
提供一下我用tool backup出來的 bin (無法在win10 工作)
[OLD2.zip](https://github.com/user-attachments/files/17981644/OLD2.zip)

**Comment by fxsheep** [comment]
dumper只是用於讀取內部ROM代碼，並非固件
我也沒有找到可用的外部固件，但是據我瞭解，使用內部ROM是可以正常運作的。
並非所有jm20339的PCB都配備了SPI Flash，有部分甚至沒有其欄位。這種設備只能用內部ROM。
